# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    container_name: track-a-tron-db
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: "tat-dev"
      POSTGRES_PASSWORD: "!password123"

    ports:
      - "55500:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "45500:8080"